# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '1.0'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
        arguments: -t sreeju:1.0
    - script: docker images
    - script: docker ps -a
    - script: docker ps
  - job: Run
    displayName: run the container
    steps:
    - task: CmdLine@2
    - script: docker run -it sreeju:1.0 echo hello
    - script: docker images
    - script: docker ps -a
    - script: docker ps