# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - none

resources:
- repo: self

variables:
  tag: '1.0'
  newrepo: 'sreeju/apline1'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: myazurereg
        repository: $(newrepo) 
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
#        arguments: -t $(newrepo)
        
    - script: docker images
    - script: docker ps -a
    - script: docker ps
#    - script: docker run $(newrepo):$(tag)
#    - script: docker ps -a
#    - script: docker ps

- stage: Run
  jobs:
  - job: Run
    displayName: run the container
    container:
     endpoint: myazurereg
     image: $(newrepo):$(tag)
     options: -n myapline -it bash
    steps:
    - task: CmdLine@2
    - script: docker images
    - script: docker ps -a
    - script: docker ps